### ISSUE TITLE
Devil May Cry weapons cause significant FPS drops when being held

### ISSUE THREAD

**Issue by Drakyl** [AzureZhen/DMC-Weapons-Mod#2]
Modpack: Bane of Dragons version 1.5.6
Modpack creater: Kreezxil
Link to pack (still in development): https://kreezcraft.com/download/bane-of-dragons-1-5-6-indev/

When Holding a Devil May Cry weapon FPS drops. switching to something else clears it. The weapons are nice to look at, but seem to have negative effects on users FPS even at low graphic settings.

**Comment by AzureDoom** [comment]
Yeah sadly a known issue. I'm looking for a way to resolve this issue.

**Comment by Drakyl** [comment]
No worries Kreezxil suggested I should let you know

**Comment by zeff9801** [comment]
It's because the weapons are high poly, you should change them with low poly weapons

**Comment by AzureDoom** [comment]
Closing as the 1.12.2 is not getting updates and being remade for 1.15.2
